---
driver:
  name: docker
  hostname: panko.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: panko
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
    - name: apache
      repo: git
      source: https://github.com/salt-formulas/salt-formula-apache
  state_top:
    base:
      "*":
        - linux.system
        - panko
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - panko
          - release
  pillars-from-files:
    linux_repo_openstack.sls: tests/pillar/repo_mcp_openstack_<%= ENV['OS_VERSION'] || 'pike' %>.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: server_cluster
    provisioner:
      pillars-from-files:
        panko.sls: tests/pillar/server_cluster.sls
      pillars:
        release.sls:
          panko:
            server:
              version: <%= ENV['OS_VERSION'] || 'pike' %>

  - name: server_single
    provisioner:
      pillars-from-files:
        panko.sls: tests/pillar/server_single.sls
      pillars:
        release.sls:
          panko:
            server:
              version: <%= ENV['OS_VERSION'] || 'pike' %>
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
